const fotos = [
  {
    title: "Akatsuki",
    src: "https://images.pexels.com/photos/1097456/pexels-photo-1097456.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "2",
    alt: "Akatsuki",
    tags: ["anime", "villanos", "misterio", "arte"],
    idUser: "1",
  },
  {
    title: "Fondo de code",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "3",
    alt: "Fondo épico",
    tags: ["tecnología", "futurista", "abstracto", "arte digital"],
    idUser: "5",
  },
  {
    title: "Shinjeki no Kiojin",
    src: "https://images.pexels.com/photos/1421903/pexels-photo-1421903.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "4",
    alt: "Attack on Titan",
    tags: ["acción", "drama", "fantasía", "épico"],
    idUser: "5",
  },
  {
    title: "Cielo Estrellado",
    src: "https://images.pexels.com/photos/585752/pexels-photo-585752.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "5",
    alt: "Cielo Estrellado",
    tags: ["noche", "naturaleza", "paisaje", "estrellas"],
    idUser: "5",
  },
  {
    title: "Montañas Nebulosas",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "6",
    alt: "Montañas Nebulosas",
    tags: ["naturaleza", "paisaje", "aventura", "exploración"],
    idUser: "1",
  },
  {
    title: "Cascada Mágica",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "7",
    alt: "Cascada Mágica",
    tags: ["agua", "naturaleza", "tranquilidad", "relajación"],
  },
  {
    title: "Arte Abstracto",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "8",
    alt: "Arte Abstracto",
    tags: ["arte", "abstracto", "colorido", "creatividad"],
  },
  {
    title: "Paseo en la Playa",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "9",
    alt: "Paseo en la Playa",
    tags: ["playa", "verano", "vacaciones", "relax"],
  },
  {
    title: "Reflejo en el Lago",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "10",
    alt: "Reflejo en el Lago",
    tags: ["agua", "reflejo", "tranquilidad", "naturaleza"],
  },
  {
    title: "Fiesta de Colores",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "11",
    alt: "Fiesta de Colores",
    tags: ["colorido", "celebración", "diversión", "festividad"],
  },
  {
    title: "Día de Lluvia",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "12",
    alt: "Día de Lluvia",
    tags: ["lluvia", "melancolía", "reflexión", "tranquilidad"],
  },
  {
    title: "Atardecer en la Montaña",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "13",
    alt: "Atardecer en la Montaña",
    tags: ["atardecer", "paisaje", "naturaleza", "paz"],
  },
  {
    title: "Gato en la Ventana",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "14",
    alt: "Gato en la Ventana",
    tags: ["mascotas", "gatos", "interiores", "tranquilidad"],
  },
  {
    title: "Café en la Mañana",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "15",
    alt: "Café en la Mañana",
    tags: ["café", "desayuno", "hogar", "tranquilidad"],
  },
  {
    title: "Bosque Encantado",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "16",
    alt: "Bosque Encantado",
    tags: ["naturaleza", "misterio", "fantasía", "exploración"],
  },
  {
    title: "Playa Tropical",
    src: "src/img/chicade-anime-posa-mientras-sostiene-un-lapiz-optico-de-computadora-otlij5ko8hp0cudp.jpg",
    id: "17",
    alt: "Playa Tropical",
    tags: ["playa", "tropical", "verano", "vacaciones"],
  },
  {
    title: "Akatsuki",
    src: "https://images.pexels.com/photos/1097456/pexels-photo-1097456.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "2",
    alt: "Akatsuki",
    tags: ["anime", "villanos", "misterio", "arte"],
    idUser: "1",
  },
  {
    title: "Fondo de code",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "3",
    alt: "Fondo épico",
    tags: ["tecnología", "futurista", "abstracto", "arte digital"],
    idUser: "5",
  },
  {
    title: "Shinjeki no Kiojin",
    src: "https://images.pexels.com/photos/1421903/pexels-photo-1421903.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "4",
    alt: "Attack on Titan",
    tags: ["acción", "drama", "fantasía", "épico"],
    idUser: "5",
  },
  {
    title: "Cielo Estrellado",
    src: "https://images.pexels.com/photos/585752/pexels-photo-585752.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "5",
    alt: "Cielo Estrellado",
    tags: ["noche", "naturaleza", "paisaje", "estrellas"],
    idUser: "5",
  },
  {
    title: "Montañas Nebulosas",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "6",
    alt: "Montañas Nebulosas",
    tags: ["naturaleza", "paisaje", "aventura", "exploración"],
    idUser: "1",
  },
  {
    title: "Cascada Mágica",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "7",
    alt: "Cascada Mágica",
    tags: ["agua", "naturaleza", "tranquilidad", "relajación"],
  },
  {
    title: "Arte Abstracto",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "8",
    alt: "Arte Abstracto",
    tags: ["arte", "abstracto", "colorido", "creatividad"],
  },
  {
    title: "Paseo en la Playa",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "9",
    alt: "Paseo en la Playa",
    tags: ["playa", "verano", "vacaciones", "relax"],
  },
  {
    title: "Reflejo en el Lago",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "10",
    alt: "Reflejo en el Lago",
    tags: ["agua", "reflejo", "tranquilidad", "naturaleza"],
  },
  {
    title: "Fiesta de Colores",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "11",
    alt: "Fiesta de Colores",
    tags: ["colorido", "celebración", "diversión", "festividad"],
  },
  {
    title: "Día de Lluvia",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "12",
    alt: "Día de Lluvia",
    tags: ["lluvia", "melancolía", "reflexión", "tranquilidad"],
  },
  {
    title: "Atardecer en la Montaña",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "13",
    alt: "Atardecer en la Montaña",
    tags: ["atardecer", "paisaje", "naturaleza", "paz"],
  },
  {
    title: "Gato en la Ventana",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "14",
    alt: "Gato en la Ventana",
    tags: ["mascotas", "gatos", "interiores", "tranquilidad"],
  },
  {
    title: "Café en la Mañana",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "15",
    alt: "Café en la Mañana",
    tags: ["café", "desayuno", "hogar", "tranquilidad"],
  },
  {
    title: "Bosque Encantado",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "16",
    alt: "Bosque Encantado",
    tags: ["naturaleza", "misterio", "fantasía", "exploración"],
  },
  {
    title: "Playa Tropical",
    src: "src/img/chicade-anime-posa-mientras-sostiene-un-lapiz-optico-de-computadora-otlij5ko8hp0cudp.jpg",
    id: "17",
    alt: "Playa Tropical",
    tags: ["playa", "tropical", "verano", "vacaciones"],
  },
  {
    title: "Akatsuki",
    src: "https://images.pexels.com/photos/1097456/pexels-photo-1097456.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "2",
    alt: "Akatsuki",
    tags: ["anime", "villanos", "misterio", "arte"],
    idUser: "1",
  },
  {
    title: "Fondo de code",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "3",
    alt: "Fondo épico",
    tags: ["tecnología", "futurista", "abstracto", "arte digital"],
    idUser: "5",
  },
  {
    title: "Shinjeki no Kiojin",
    src: "https://images.pexels.com/photos/1421903/pexels-photo-1421903.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "4",
    alt: "Attack on Titan",
    tags: ["acción", "drama", "fantasía", "épico"],
    idUser: "5",
  },
  {
    title: "Cielo Estrellado",
    src: "https://images.pexels.com/photos/585752/pexels-photo-585752.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "5",
    alt: "Cielo Estrellado",
    tags: ["noche", "naturaleza", "paisaje", "estrellas"],
    idUser: "5",
  },
  {
    title: "Montañas Nebulosas",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "6",
    alt: "Montañas Nebulosas",
    tags: ["naturaleza", "paisaje", "aventura", "exploración"],
    idUser: "1",
  },
  {
    title: "Cascada Mágica",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "7",
    alt: "Cascada Mágica",
    tags: ["agua", "naturaleza", "tranquilidad", "relajación"],
  },
  {
    title: "Arte Abstracto",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "8",
    alt: "Arte Abstracto",
    tags: ["arte", "abstracto", "colorido", "creatividad"],
  },
  {
    title: "Paseo en la Playa",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "9",
    alt: "Paseo en la Playa",
    tags: ["playa", "verano", "vacaciones", "relax"],
  },
  {
    title: "Reflejo en el Lago",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "10",
    alt: "Reflejo en el Lago",
    tags: ["agua", "reflejo", "tranquilidad", "naturaleza"],
  },
  {
    title: "Fiesta de Colores",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "11",
    alt: "Fiesta de Colores",
    tags: ["colorido", "celebración", "diversión", "festividad"],
  },
  {
    title: "Día de Lluvia",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "12",
    alt: "Día de Lluvia",
    tags: ["lluvia", "melancolía", "reflexión", "tranquilidad"],
  },
  {
    title: "Atardecer en la Montaña",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "13",
    alt: "Atardecer en la Montaña",
    tags: ["atardecer", "paisaje", "naturaleza", "paz"],
  },
  {
    title: "Gato en la Ventana",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "14",
    alt: "Gato en la Ventana",
    tags: ["mascotas", "gatos", "interiores", "tranquilidad"],
  },
  {
    title: "Café en la Mañana",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "15",
    alt: "Café en la Mañana",
    tags: ["café", "desayuno", "hogar", "tranquilidad"],
  },
  {
    title: "Bosque Encantado",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "16",
    alt: "Bosque Encantado",
    tags: ["naturaleza", "misterio", "fantasía", "exploración"],
  },
  {
    title: "Playa Tropical",
    src: "src/img/chicade-anime-posa-mientras-sostiene-un-lapiz-optico-de-computadora-otlij5ko8hp0cudp.jpg",
    id: "17",
    alt: "Playa Tropical",
    tags: ["playa", "tropical", "verano", "vacaciones"],
  },
  {
    title: "Akatsuki",
    src: "https://images.pexels.com/photos/1097456/pexels-photo-1097456.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "2",
    alt: "Akatsuki",
    tags: ["anime", "villanos", "misterio", "arte"],
    idUser: "1",
  },
  {
    title: "Fondo de code",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "3",
    alt: "Fondo épico",
    tags: ["tecnología", "futurista", "abstracto", "arte digital"],
    idUser: "5",
  },
  {
    title: "Shinjeki no Kiojin",
    src: "https://images.pexels.com/photos/1421903/pexels-photo-1421903.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "4",
    alt: "Attack on Titan",
    tags: ["acción", "drama", "fantasía", "épico"],
    idUser: "5",
  },
  {
    title: "Cielo Estrellado",
    src: "https://images.pexels.com/photos/585752/pexels-photo-585752.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "5",
    alt: "Cielo Estrellado",
    tags: ["noche", "naturaleza", "paisaje", "estrellas"],
    idUser: "5",
  },
  {
    title: "Montañas Nebulosas",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "6",
    alt: "Montañas Nebulosas",
    tags: ["naturaleza", "paisaje", "aventura", "exploración"],
    idUser: "1",
  },
  {
    title: "Cascada Mágica",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "7",
    alt: "Cascada Mágica",
    tags: ["agua", "naturaleza", "tranquilidad", "relajación"],
  },
  {
    title: "Arte Abstracto",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "8",
    alt: "Arte Abstracto",
    tags: ["arte", "abstracto", "colorido", "creatividad"],
  },
  {
    title: "Paseo en la Playa",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "9",
    alt: "Paseo en la Playa",
    tags: ["playa", "verano", "vacaciones", "relax"],
  },
  {
    title: "Reflejo en el Lago",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "10",
    alt: "Reflejo en el Lago",
    tags: ["agua", "reflejo", "tranquilidad", "naturaleza"],
  },
  {
    title: "Fiesta de Colores",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "11",
    alt: "Fiesta de Colores",
    tags: ["colorido", "celebración", "diversión", "festividad"],
  },
  {
    title: "Día de Lluvia",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "12",
    alt: "Día de Lluvia",
    tags: ["lluvia", "melancolía", "reflexión", "tranquilidad"],
  },
  {
    title: "Atardecer en la Montaña",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "13",
    alt: "Atardecer en la Montaña",
    tags: ["atardecer", "paisaje", "naturaleza", "paz"],
  },
  {
    title: "Gato en la Ventana",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "14",
    alt: "Gato en la Ventana",
    tags: ["mascotas", "gatos", "interiores", "tranquilidad"],
  },
  {
    title: "Café en la Mañana",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "15",
    alt: "Café en la Mañana",
    tags: ["café", "desayuno", "hogar", "tranquilidad"],
  },
  {
    title: "Bosque Encantado",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "16",
    alt: "Bosque Encantado",
    tags: ["naturaleza", "misterio", "fantasía", "exploración"],
  },
  {
    title: "Playa Tropical",
    src: "src/img/chicade-anime-posa-mientras-sostiene-un-lapiz-optico-de-computadora-otlij5ko8hp0cudp.jpg",
    id: "17",
    alt: "Playa Tropical",
    tags: ["playa", "tropical", "verano", "vacaciones"],
  },
  {
    title: "Akatsuki",
    src: "https://images.pexels.com/photos/1097456/pexels-photo-1097456.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "2",
    alt: "Akatsuki",
    tags: ["anime", "villanos", "misterio", "arte"],
    idUser: "1",
  },
  {
    title: "Fondo de code",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "3",
    alt: "Fondo épico",
    tags: ["tecnología", "futurista", "abstracto", "arte digital"],
    idUser: "5",
  },
  {
    title: "Shinjeki no Kiojin",
    src: "https://images.pexels.com/photos/1421903/pexels-photo-1421903.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "4",
    alt: "Attack on Titan",
    tags: ["acción", "drama", "fantasía", "épico"],
    idUser: "5",
  },
  {
    title: "Cielo Estrellado",
    src: "https://images.pexels.com/photos/585752/pexels-photo-585752.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "5",
    alt: "Cielo Estrellado",
    tags: ["noche", "naturaleza", "paisaje", "estrellas"],
    idUser: "5",
  },
  {
    title: "Montañas Nebulosas",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "6",
    alt: "Montañas Nebulosas",
    tags: ["naturaleza", "paisaje", "aventura", "exploración"],
    idUser: "1",
  },
  {
    title: "Cascada Mágica",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "7",
    alt: "Cascada Mágica",
    tags: ["agua", "naturaleza", "tranquilidad", "relajación"],
  },
  {
    title: "Arte Abstracto",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "8",
    alt: "Arte Abstracto",
    tags: ["arte", "abstracto", "colorido", "creatividad"],
  },
  {
    title: "Paseo en la Playa",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "9",
    alt: "Paseo en la Playa",
    tags: ["playa", "verano", "vacaciones", "relax"],
  },
  {
    title: "Reflejo en el Lago",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "10",
    alt: "Reflejo en el Lago",
    tags: ["agua", "reflejo", "tranquilidad", "naturaleza"],
  },
  {
    title: "Fiesta de Colores",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "11",
    alt: "Fiesta de Colores",
    tags: ["colorido", "celebración", "diversión", "festividad"],
  },
  {
    title: "Día de Lluvia",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "12",
    alt: "Día de Lluvia",
    tags: ["lluvia", "melancolía", "reflexión", "tranquilidad"],
  },
  {
    title: "Atardecer en la Montaña",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "13",
    alt: "Atardecer en la Montaña",
    tags: ["atardecer", "paisaje", "naturaleza", "paz"],
  },
  {
    title: "Gato en la Ventana",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "14",
    alt: "Gato en la Ventana",
    tags: ["mascotas", "gatos", "interiores", "tranquilidad"],
  },
  {
    title: "Café en la Mañana",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "15",
    alt: "Café en la Mañana",
    tags: ["café", "desayuno", "hogar", "tranquilidad"],
  },
  {
    title: "Bosque Encantado",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "16",
    alt: "Bosque Encantado",
    tags: ["naturaleza", "misterio", "fantasía", "exploración"],
  },
  {
    title: "Playa Tropical",
    src: "src/img/chicade-anime-posa-mientras-sostiene-un-lapiz-optico-de-computadora-otlij5ko8hp0cudp.jpg",
    id: "17",
    alt: "Playa Tropical",
    tags: ["playa", "tropical", "verano", "vacaciones"],
  },
  {
    title: "Akatsuki",
    src: "https://images.pexels.com/photos/1097456/pexels-photo-1097456.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "2",
    alt: "Akatsuki",
    tags: ["anime", "villanos", "misterio", "arte"],
    idUser: "1",
  },
  {
    title: "Fondo de code",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "3",
    alt: "Fondo épico",
    tags: ["tecnología", "futurista", "abstracto", "arte digital"],
    idUser: "5",
  },
  {
    title: "Shinjeki no Kiojin",
    src: "https://images.pexels.com/photos/1421903/pexels-photo-1421903.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "4",
    alt: "Attack on Titan",
    tags: ["acción", "drama", "fantasía", "épico"],
    idUser: "5",
  },
  {
    title: "Cielo Estrellado",
    src: "https://images.pexels.com/photos/585752/pexels-photo-585752.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "5",
    alt: "Cielo Estrellado",
    tags: ["noche", "naturaleza", "paisaje", "estrellas"],
    idUser: "5",
  },
  {
    title: "Montañas Nebulosas",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "6",
    alt: "Montañas Nebulosas",
    tags: ["naturaleza", "paisaje", "aventura", "exploración"],
    idUser: "1",
  },
  {
    title: "Cascada Mágica",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "7",
    alt: "Cascada Mágica",
    tags: ["agua", "naturaleza", "tranquilidad", "relajación"],
  },
  {
    title: "Arte Abstracto",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "8",
    alt: "Arte Abstracto",
    tags: ["arte", "abstracto", "colorido", "creatividad"],
  },
  {
    title: "Paseo en la Playa",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "9",
    alt: "Paseo en la Playa",
    tags: ["playa", "verano", "vacaciones", "relax"],
  },
  {
    title: "Reflejo en el Lago",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "10",
    alt: "Reflejo en el Lago",
    tags: ["agua", "reflejo", "tranquilidad", "naturaleza"],
  },
  {
    title: "Fiesta de Colores",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "11",
    alt: "Fiesta de Colores",
    tags: ["colorido", "celebración", "diversión", "festividad"],
  },
  {
    title: "Día de Lluvia",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "12",
    alt: "Día de Lluvia",
    tags: ["lluvia", "melancolía", "reflexión", "tranquilidad"],
  },
  {
    title: "Atardecer en la Montaña",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "13",
    alt: "Atardecer en la Montaña",
    tags: ["atardecer", "paisaje", "naturaleza", "paz"],
  },
  {
    title: "Gato en la Ventana",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "14",
    alt: "Gato en la Ventana",
    tags: ["mascotas", "gatos", "interiores", "tranquilidad"],
  },
  {
    title: "Café en la Mañana",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "15",
    alt: "Café en la Mañana",
    tags: ["café", "desayuno", "hogar", "tranquilidad"],
  },
  {
    title: "Bosque Encantado",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "16",
    alt: "Bosque Encantado",
    tags: ["naturaleza", "misterio", "fantasía", "exploración"],
  },
  {
    title: "Playa Tropical",
    src: "src/img/chicade-anime-posa-mientras-sostiene-un-lapiz-optico-de-computadora-otlij5ko8hp0cudp.jpg",
    id: "17",
    alt: "Playa Tropical",
    tags: ["playa", "tropical", "verano", "vacaciones"],
  },
  {
    title: "Akatsuki",
    src: "https://images.pexels.com/photos/1097456/pexels-photo-1097456.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "2",
    alt: "Akatsuki",
    tags: ["anime", "villanos", "misterio", "arte"],
    idUser: "1",
  },
  {
    title: "Fondo de code",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "3",
    alt: "Fondo épico",
    tags: ["tecnología", "futurista", "abstracto", "arte digital"],
    idUser: "5",
  },
  {
    title: "Shinjeki no Kiojin",
    src: "https://images.pexels.com/photos/1421903/pexels-photo-1421903.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "4",
    alt: "Attack on Titan",
    tags: ["acción", "drama", "fantasía", "épico"],
    idUser: "5",
  },
  {
    title: "Cielo Estrellado",
    src: "https://images.pexels.com/photos/585752/pexels-photo-585752.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "5",
    alt: "Cielo Estrellado",
    tags: ["noche", "naturaleza", "paisaje", "estrellas"],
    idUser: "5",
  },
  {
    title: "Montañas Nebulosas",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "6",
    alt: "Montañas Nebulosas",
    tags: ["naturaleza", "paisaje", "aventura", "exploración"],
    idUser: "1",
  },
  {
    title: "Cascada Mágica",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "7",
    alt: "Cascada Mágica",
    tags: ["agua", "naturaleza", "tranquilidad", "relajación"],
  },
  {
    title: "Arte Abstracto",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "8",
    alt: "Arte Abstracto",
    tags: ["arte", "abstracto", "colorido", "creatividad"],
  },
  {
    title: "Paseo en la Playa",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "9",
    alt: "Paseo en la Playa",
    tags: ["playa", "verano", "vacaciones", "relax"],
  },
  {
    title: "Reflejo en el Lago",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "10",
    alt: "Reflejo en el Lago",
    tags: ["agua", "reflejo", "tranquilidad", "naturaleza"],
  },
  {
    title: "Fiesta de Colores",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "11",
    alt: "Fiesta de Colores",
    tags: ["colorido", "celebración", "diversión", "festividad"],
  },
  {
    title: "Día de Lluvia",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "12",
    alt: "Día de Lluvia",
    tags: ["lluvia", "melancolía", "reflexión", "tranquilidad"],
  },
  {
    title: "Atardecer en la Montaña",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "13",
    alt: "Atardecer en la Montaña",
    tags: ["atardecer", "paisaje", "naturaleza", "paz"],
  },
  {
    title: "Gato en la Ventana",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "14",
    alt: "Gato en la Ventana",
    tags: ["mascotas", "gatos", "interiores", "tranquilidad"],
  },
  {
    title: "Café en la Mañana",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "15",
    alt: "Café en la Mañana",
    tags: ["café", "desayuno", "hogar", "tranquilidad"],
  },
  {
    title: "Bosque Encantado",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "16",
    alt: "Bosque Encantado",
    tags: ["naturaleza", "misterio", "fantasía", "exploración"],
  },
  {
    title: "Playa Tropical",
    src: "src/img/chicade-anime-posa-mientras-sostiene-un-lapiz-optico-de-computadora-otlij5ko8hp0cudp.jpg",
    id: "17",
    alt: "Playa Tropical",
    tags: ["playa", "tropical", "verano", "vacaciones"],
  },
  {
    title: "Akatsuki",
    src: "https://images.pexels.com/photos/1097456/pexels-photo-1097456.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "2",
    alt: "Akatsuki",
    tags: ["anime", "villanos", "misterio", "arte"],
    idUser: "1",
  },
  {
    title: "Fondo de code",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "3",
    alt: "Fondo épico",
    tags: ["tecnología", "futurista", "abstracto", "arte digital"],
    idUser: "5",
  },
  {
    title: "Shinjeki no Kiojin",
    src: "https://images.pexels.com/photos/1421903/pexels-photo-1421903.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "4",
    alt: "Attack on Titan",
    tags: ["acción", "drama", "fantasía", "épico"],
    idUser: "5",
  },
  {
    title: "Cielo Estrellado",
    src: "https://images.pexels.com/photos/585752/pexels-photo-585752.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "5",
    alt: "Cielo Estrellado",
    tags: ["noche", "naturaleza", "paisaje", "estrellas"],
    idUser: "5",
  },
  {
    title: "Montañas Nebulosas",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "6",
    alt: "Montañas Nebulosas",
    tags: ["naturaleza", "paisaje", "aventura", "exploración"],
    idUser: "1",
  },
  {
    title: "Cascada Mágica",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "7",
    alt: "Cascada Mágica",
    tags: ["agua", "naturaleza", "tranquilidad", "relajación"],
  },
  {
    title: "Arte Abstracto",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "8",
    alt: "Arte Abstracto",
    tags: ["arte", "abstracto", "colorido", "creatividad"],
  },
  {
    title: "Paseo en la Playa",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "9",
    alt: "Paseo en la Playa",
    tags: ["playa", "verano", "vacaciones", "relax"],
  },
  {
    title: "Reflejo en el Lago",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "10",
    alt: "Reflejo en el Lago",
    tags: ["agua", "reflejo", "tranquilidad", "naturaleza"],
  },
  {
    title: "Fiesta de Colores",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "11",
    alt: "Fiesta de Colores",
    tags: ["colorido", "celebración", "diversión", "festividad"],
  },
  {
    title: "Día de Lluvia",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "12",
    alt: "Día de Lluvia",
    tags: ["lluvia", "melancolía", "reflexión", "tranquilidad"],
  },
  {
    title: "Atardecer en la Montaña",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "13",
    alt: "Atardecer en la Montaña",
    tags: ["atardecer", "paisaje", "naturaleza", "paz"],
  },
  {
    title: "Gato en la Ventana",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "14",
    alt: "Gato en la Ventana",
    tags: ["mascotas", "gatos", "interiores", "tranquilidad"],
  },
  {
    title: "Café en la Mañana",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "15",
    alt: "Café en la Mañana",
    tags: ["café", "desayuno", "hogar", "tranquilidad"],
  },
  {
    title: "Bosque Encantado",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "16",
    alt: "Bosque Encantado",
    tags: ["naturaleza", "misterio", "fantasía", "exploración"],
  },
  {
    title: "Playa Tropical",
    src: "src/img/chicade-anime-posa-mientras-sostiene-un-lapiz-optico-de-computadora-otlij5ko8hp0cudp.jpg",
    id: "17",
    alt: "Playa Tropical",
    tags: ["playa", "tropical", "verano", "vacaciones"],
  },
  {
    title: "Akatsuki",
    src: "https://images.pexels.com/photos/1097456/pexels-photo-1097456.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "2",
    alt: "Akatsuki",
    tags: ["anime", "villanos", "misterio", "arte"],
    idUser: "1",
  },
  {
    title: "Fondo de code",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "3",
    alt: "Fondo épico",
    tags: ["tecnología", "futurista", "abstracto", "arte digital"],
    idUser: "5",
  },
  {
    title: "Shinjeki no Kiojin",
    src: "https://images.pexels.com/photos/1421903/pexels-photo-1421903.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "4",
    alt: "Attack on Titan",
    tags: ["acción", "drama", "fantasía", "épico"],
    idUser: "5",
  },
  {
    title: "Cielo Estrellado",
    src: "https://images.pexels.com/photos/585752/pexels-photo-585752.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "5",
    alt: "Cielo Estrellado",
    tags: ["noche", "naturaleza", "paisaje", "estrellas"],
    idUser: "5",
  },
  {
    title: "Montañas Nebulosas",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "6",
    alt: "Montañas Nebulosas",
    tags: ["naturaleza", "paisaje", "aventura", "exploración"],
    idUser: "1",
  },
  {
    title: "Cascada Mágica",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "7",
    alt: "Cascada Mágica",
    tags: ["agua", "naturaleza", "tranquilidad", "relajación"],
  },
  {
    title: "Arte Abstracto",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "8",
    alt: "Arte Abstracto",
    tags: ["arte", "abstracto", "colorido", "creatividad"],
  },
  {
    title: "Paseo en la Playa",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "9",
    alt: "Paseo en la Playa",
    tags: ["playa", "verano", "vacaciones", "relax"],
  },
  {
    title: "Reflejo en el Lago",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "10",
    alt: "Reflejo en el Lago",
    tags: ["agua", "reflejo", "tranquilidad", "naturaleza"],
  },
  {
    title: "Fiesta de Colores",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "11",
    alt: "Fiesta de Colores",
    tags: ["colorido", "celebración", "diversión", "festividad"],
  },
  {
    title: "Día de Lluvia",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "12",
    alt: "Día de Lluvia",
    tags: ["lluvia", "melancolía", "reflexión", "tranquilidad"],
  },
  {
    title: "Atardecer en la Montaña",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "13",
    alt: "Atardecer en la Montaña",
    tags: ["atardecer", "paisaje", "naturaleza", "paz"],
  },
  {
    title: "Gato en la Ventana",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "14",
    alt: "Gato en la Ventana",
    tags: ["mascotas", "gatos", "interiores", "tranquilidad"],
  },
  {
    title: "Café en la Mañana",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "15",
    alt: "Café en la Mañana",
    tags: ["café", "desayuno", "hogar", "tranquilidad"],
  },
  {
    title: "Bosque Encantado",
    src: "https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    id: "16",
    alt: "Bosque Encantado",
    tags: ["naturaleza", "misterio", "fantasía", "exploración"],
  },
  {
    title: "Playa Tropical",
    src: "src/img/chicade-anime-posa-mientras-sostiene-un-lapiz-optico-de-computadora-otlij5ko8hp0cudp.jpg",
    id: "17",
    alt: "Playa Tropical",
    tags: ["playa", "tropical", "verano", "vacaciones"],
  },
];

export default fotos;
